name: commitLint

on: [pull_request]

jobs:
    commitlint-pull_request:
        runs-on: ubuntu-latest

        steps:
            - name: create workflow for commitLint
              uses: ./.github/workflows/commitLintBody.yml

            - name: check PR using commitlint
              run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~1 --to ${{ github.event.pull_request.head.sha }} --verbose
