name: commitLint

on: [workflow_call]

jobs:
    commitlint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  cache: "npm"

            - name: install commitlint
              run: |
                  npm install conventional-changelog-conventionalcommits
                  npm install commitlint@latest
                  npm install @commitlint/config-conventional
