name: ci

on: pull_request

jobs:
    commitlint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  cache: "npm"

            - name: install commitlint
              run: |
                  npm install conventional-changelog-conventionalcommits
                  npm install commitlint@latest
                  npm install @commitlint/config-conventional

            - name: check PR using commitlint
              run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~1 --to ${{ github.event.pull_request.head.sha }} --verbose

    tests-unit:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  cache: "npm"

            - name: install dependencies
              run: npm ci

            - name: run unit tests
              run: npm run test-ci

            - name: save artifacts
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: jest-report
                  path: test-report.html

    tests-e2e:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  cache: "npm"

            - name: install dependencies
              run: npm ci

            - name: run e2e tests
              run: npm run test-e2e-ci

            - name: save artifacts
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: playwright-report
                  path: playwright-report
