name: release

on:
    push:
        tags:
            - "v[0-9]+"

permissions:
    contents: write
    issues: write

jobs:
    tests:
        uses: ./.github/workflows/tests.yml

    release:
        needs: tests

        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: create changelog
              id: changelog_step
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ github.token }}
                  tag: ${{ github.ref_name }}
                  writeToFile: false

            - name: create or update issue
              id: issue_step
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_VERSION: ${{ github.ref_name }}
                  RELEASE_AUTHOR: ${{ github.actor }}
                  RELEASE_DATE: ${{ github.event.head_commit.timestamp }}
                  RELEASE_CHANGELOG: ${{ steps.changelog_step.outputs.changes }}
                  RELEASE_TESTS_NUM: ${{ github.run_id }}
                  RELEASE_TESTS_RESULT_MSG: Report files of tests can be loaded from this [link](${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}) (Artifacts section).
              with:
                  filename: .github/ISSUE_TEMPLATE.md
                  update_existing: true
                  search_existing: all

        outputs:
            issueNum: ${{ steps.issue_step.outputs.number }}

    build-and-deploy:
        needs: release

        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"
                  cache: "npm"

            - name: install dependecies and build
              run: |
                  npm ci
                  npm run build

            - name: deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build

            - name: Comment issue with deploy
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ needs.release.outputs.issueNum }}
                  body: |
                      ## Deploy № **${{ github.run_id }}**
                      [Link to deploy](https://liestreadt.github.io/shri-unit-demo-cra/)
                      P.S. Wait couple minutes after this message
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Close Issue
              uses: peter-evans/close-issue@v3
              with:
                  issue-number: ${{ needs.release.outputs.issueNum }}
                  comment: |
                      ## Successfull deployment. Issue automatically closed.
