name: release

on:
    push:
        tags:
            - "v[0-9]+"

permissions:
    contents: read
    issues: write

jobs:
    # tests:
    #     uses: ./.github/workflows/tests.yml

    release:
        # needs: tests

        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: create changelog
              id: changelog_step
              uses: ardalanamini/auto-changelog@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  mention-authors: true
                  include-compare-link: true
                  include-pr-links: true
                  include-commit-links: true
                  semver: false
                  use-github-autolink: true

            - name: get information for release
              run: |
                  echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
                  echo "RELEASE_AUTHOR=${{ github.actor }}" >> $GITHUB_ENV
                  echo "RELEASE_DATE=${{ github.event.head_commit.timestamp }}"
                  echo "RELEASE_CHANGELOG=${{ steps.changelog_step.output.changelog}}"

            - name: create or update issue
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  filename: .github/ISSUE_TEMPLATE.md
                  update_existing: true
                  search_existing: all
