name: release

on:
    push:
        tags:
            - "v[0-9]+"

permissions:
    contents: read
    issues: write

jobs:
    tests:
        uses: ./.github/workflows/tests.yml

    release:
        needs: tests

        runs-on: ubuntu-latest

        steps:
            - name: checkout repo to actions
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: create changelog
              id: changelog_step
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ github.token }}
                  tag: ${{ github.ref_name }}
                  writeToFile: false

            - name: create or update issue
              id: issue_step
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_VERSION: ${{ github.ref_name }}
                  RELEASE_AUTHOR: ${{ github.actor }}
                  RELEASE_DATE: ${{ github.event.head_commit.timestamp }}
                  RELEASE_CHANGELOG: ${{ steps.changelog_step.outputs.changes }}
              with:
                  filename: .github/ISSUE_TEMPLATE.md
                  update_existing: true
                  search_existing: all

            - name: add tests result to issue
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ steps.issue_step.outputs.number }}
                  body: |
                      ## ${{ github.run_id }} tests result
                      Report files of tests can be loaded from this [link](${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}) (Artifacts section).

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
